language: php
sudo: false

php:
  - "7.1"
  - "7.2"
  - "7.3"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --no-interaction

script:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; else vendor/bin/phpunit; fi
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/php-cs-fixer fix --config=vendor/ixocreate/coding-standard/.php_cs -v --dry-run --using-cache=no --path-mode=intersection `git diff --name-only --diff-filter=ACMRTUXB $TRAVIS_COMMIT_RANGE`; fi

after_success:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then php vendor/bin/php-coveralls -v; fi

notifications:
  email: false
  slack:
    secure: "et/t6QQhlrFpjBwK8AXQLagVzoN9CYyjIHbOlqRFK35rSA3g5+X8emJ3857x6TBwPbXe9RqcKs/bPlXHZnfNlHrUQSBCCtj1kr9vilLflMZ9Lm8k9dn1MsArtDLnkahkyfKNNsPINF2Rrj1zAN5UJ1fBIWATmpwvg7UK6c+N24h3nFxofAEQMre61aQ6tsD5CBFMQOLgca2qTTs1cgcvyQ2/iSLIqUq51fbG7Bv6e9nfvxIc2stTgzQzGgxDytrT5+h1rzPhRQKKCvkGsT9VeFvlfif/QHTp94yWCilLxXdj7fbd6JT5oOxugA5VK+0lU1Iao3CvU1EjZWRe7x0dx54/OlBUrqU1GtCZtUckzY+TU+r1CVIIxx2RJKEdmsmH8THHqZG6ZotfF5W5rJ0BCSv/3G1pQ1Vw8mOYojFK9FUacoKb3RI33NFQeUGZ8NB/VB1zpllY5bPmbPWCgMYjVtJjnJesonxQvdNEF45e1IlwfTbwcXzd7x3uA9y2ubBvPSAOM53yho2UfVdRs4x6Z/3WS/ypM00Agx8gdp2uYk6XC/MRtA1oyhxWJugKa4hNHPsCMWmxU2MXFZ8auBnzVdUnXcLctXVrNlhnpmTXVXGHNnzJ/ii782Cljj8VKQpi7YDJizDIXN0C+IYsZg2VljEX2op8xlan+gUoYgotu1s="
